In [1]:
import numpy as np 


In [2]:
one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
print(one_dimensional_array)

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


In [3]:
two_dimensional_array = np.array([[6, 5], [11, 7], [4, 8]])
print(two_dimensional_array)

[[ 6  5]
 [11  7]
 [ 4  8]]


In [4]:
sequence_of_integers = np.arange(5, 12)
print(sequence_of_integers)

[ 5  6  7  8  9 10 11]


In [5]:
sequence_of_integers = np.arange(5, 12)
print(sequence_of_integers)


[ 5  6  7  8  9 10 11]


In [6]:
random_integers_between_50_and_100 = np.random.randint(low=50, high=101, size=(6))
print(random_integers_between_50_and_100)

[93 93 91 59 65 91]


In [7]:
random_floats_between_0_and_1 = np.random.random([6])
print(random_floats_between_0_and_1) 

[0.80733765 0.67125171 0.28588725 0.41634859 0.44302126 0.71120713]


In [10]:
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_floats_between_2_and_3)

[2.80733765 2.67125171 2.28588725 2.41634859 2.44302126 2.71120713]


In [12]:
random_integers_between_10_and_00 = random_integers_between_50_and_100 * 3
print(random_integers_between_10_and_00)

[279 279 273 177 195 273]


In [16]:
feature=np.arange(6,21)

In [18]:
print(feature)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [19]:
label=(feature*3)+4
print(label)

[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


In [20]:
noise = (np.random.random([15]) * 4) - 2
print(noise)
label = label + noise 
print(label)

[ 0.58100577 -0.02121804 -0.73791428 -1.32364764  1.09803662 -0.58923742
  1.78603873  1.43233577  0.6022515   0.43933508 -0.35849432 -1.72293181
 -0.10938167 -1.24108776  0.77502222]
[22.58100577 24.97878196 27.26208572 29.67635236 35.09803662 36.41076258
 41.78603873 44.43233577 46.6022515  49.43933508 51.64150568 53.27706819
 57.89061833 59.75891224 64.77502222]


In [21]:
import numpy as np
import pandas as pd

In [24]:
my_data= np.array([[0, 3], [10, 7], [20, 9], [30, 14], [40, 15]])
my_column_names = ['temperature', 'activity']
my_dataframe = pd.DataFrame(data=my_data, columns=my_column_names)
print(my_dataframe)


   temperature  activity
0            0         3
1           10         7
2           20         9
3           30        14
4           40        15


In [28]:
my_dataframe["adjusted"] = my_dataframe["activity"] +2



print(my_dataframe)

   temperature  activity  adjusted
0            0         3         5
1           10         7         9
2           20         9        11
3           30        14        16
4           40        15        17


In [29]:
print("Rows #0, #1, and #2:")
print(my_dataframe.head(3), '\n')

print("Row #2:")
print(my_dataframe.iloc[[2]], '\n')

print("Rows #1, #2, and #3:")
print(my_dataframe[1:4], '\n')

print("Column 'temperature':")
print(my_dataframe['temperature'])

Rows #0, #1, and #2:
   temperature  activity  adjusted
0            0         3         5
1           10         7         9
2           20         9        11 

Row #2:
   temperature  activity  adjusted
2           20         9        11 

Rows #1, #2, and #3:
   temperature  activity  adjusted
1           10         7         9
2           20         9        11
3           30        14        16 

Column 'temperature':
0     0
1    10
2    20
3    30
4    40
Name: temperature, dtype: int32


In [38]:
my_data = np.array(np.random.randint(low=0, high=101, size=(3, 4)))

my_column_names = ['Eleanor',' Chidi', 'Tahani',  'Jason']
my_dataframe = pd.DataFrame(data=my_data, columns=my_column_names)


print(my_dataframe)

   Eleanor   Chidi  Tahani  Jason
0       34      72       8     10
1       17      41      38     35
2       35      32      79     89


In [39]:
my_dataframe['Janet']=my_dataframe['Tahani']+my_dataframe['Jason']
print(my_dataframe)

   Eleanor   Chidi  Tahani  Jason  Janet
0       34      72       8     10     18
1       17      41      38     35     73
2       35      32      79     89    168


In [44]:
print("  Starting value of df: %d" % my_dataframe['Jason'][1])
reference_to_df = my_dataframe

  Starting value of df: 40


In [45]:
reference_to_df = my_dataframe
my_dataframe.at[1, 'Jason'] =my_dataframe['Jason'][1] + 5
print("  Updated df: %d" % my_dataframe['Jason'][1])
print("  Updated reference_to_df: %d\n\n" % reference_to_df['Jason'][1])


print("Experiment with a true copy:")
copy_of_my_dataframe = my_dataframe.copy()

# Print the starting value of a particular cell.
print("  Starting value of my_dataframe: %d" % my_dataframe['activity'][1])
print("  Starting value of copy_of_my_dataframe: %d\n" % copy_of_my_dataframe['activity'][1])

# Modify a cell in df.
my_dataframe.at[1, 'activity'] = my_dataframe['activity'][1] + 3
print("  Updated my_dataframe: %d" % my_dataframe['activity'][1])
print("  copy_of_my_dataframe does not get updated: %d" % copy_of_my_dataframe['activity'][1])

  Updated df: 45
  Updated reference_to_df: 45


Experiment with a true copy:


KeyError: 'activity'